---
flume_agent:
  name: agent
  channels:
    - name: memoryChannel
      type: memory
      capacity: 100
  sources:
    - name: execSource
      type: exec
      command: "tail -F {{ log_file }}"
      batchSize: 1
      channels: memoryChannel
      interceptors: itime ihost itype
      interceptors.itime.type: timestamp
      interceptors.ihost.type: host
      interceptors.ihost.useIP: false
      interceptors.ihost.hostHeader: host
      interceptors.itype.type: static
      interceptors.itype.key: log_type
      interceptors.itype.value: apache_access_combined
  sinks:
    - name: avroSink
      type: avro
      hostname: '193.166.25.11'
      port: 4141
      batchSize: 10
      channel: memoryChannel
